### ISSUE TITLE
Django-Rest

### ISSUE THREAD

**Issue by Bernardoow** [django-request/django-request#136]
Its works with framework django-rest?

**Comment by stevelacey** [comment]
Yes, and if you're interested in  *just* DRF requests – the way I (lazily) did that was to extend the middleware with my own tweaked version that checks if the response is going to be JSON – you could check the subdomain or path prefix if that suits your needs better.

```py
from request import middleware

class RequestMiddleware(middleware.RequestMiddleware):
    def process_response(self, request, response):
        if 'json' not in response.get('Content-Type', 'application/json'):
            return response

        return super().process_response(request, response)
```

**Note:** the reason I also default to assuming JSON with the call to `get` is because `204 No Content` requests (e.g. `DELETE`'s) don't have a `Content-Type`

**Comment by kylef** [comment]
I think you can also achieve the same using `IGNORE_PATHS`. You could add ignore path for anything that doesn't start with `^/api$` or the path used for your API. This can be done with regex [negative lookahead](http://www.regular-expressions.info/lookaround.html).
